services:

  clamav:
    image: clamav/clamav
    container_name: clamav
    volumes:
      - ./clamav/data:/var/lib/clamav
      - ./clamav/socket:/tmp/
      - ./clamav/files:/var/www
    ports:
      - "3310:3310"